q_say:
  - "say" # Non-3sing present, habitual
  - "says" # 3sing present
  - "saying" # present participle
  - "said" # simple past tense

q_go: # present participle omitted for semantic infrequency
  - "go" # Non-3sing present, habitual
  - "goes" # 3sing present
  - "went" # simple past tense

q_tell: # must be followed by an object
 - "tell" # Non-3sing present, habitual
 - "tells" # 3sing present
 - "telling" # present participle
 - "told" # simple past tense

copula: # forms of copula for combination with 'all' or 'like'
 - "be" # habitual
 - "is" # 3sing present
 - "I'm" #1P present, contracted
 - "'s" # 3sing present
 - "was" # past
 - "were" # plural past

pron: # bare q_all/q_like must be preceded by pronouns
 - "I" # 1P-sing
 - "you" #2P
 - "we" #1P-PL
 - "she" #3sing
 - "he" #3sing
 - "they" #3PL

intj:
 - ah
 - ay
 - eh
 - ha
 - hey
 - hm
 - huh
 - man
 - mm
 - oh
 - uh
 - um
 - yo
 - wow