q_say:
  - "(had said)" # preterite past
  - "((am|be|was|were) sayin('|g))" # be V+ing
  - "say" # unmarked
  - "says" # -s
  - "sayin('|g)" # V+ing
  - "said" # past

q_go: 
  - "(had went)" # preterite past tense
  - "((am|be|was|were) goin('|g))" # be V+ing
  - "go" # Non-3sing present, habitual
  - "goes" # 3sing present
  - "goin('|g)" # V+ing
  - "went" # simple past tense

q_tell: # must be followed by an object
 - "(had told)" # preterite past tense
 - "((am|be|was|were) tellin('|g))" # be V+ing
 - "tell" # Non-3sing present, habitual
 - "tells" # 3sing present
 - "tellin('|g)" # V+ing
 - "told" # simple past tense
 

q_think:
 - "(had thought)" # preterite past tense
 - "((am|be|was|were) thinkin('|g))" # be V+ing
 - "think" # Non-3sing present, habitual
 - "thinks" # 3sing present
 - "thinkin('|g)" # V+ing
 - "thought" # simple past tense
 

q_ask:
 - "(had asked)" # preterite past tense
 - "((am|be|was|were) askin('|g))" # be V+ing
 - "ask" # Non-3sing present, habitual
 - "asks" # 3sing present
 - "askin('|g)" # V+ing
 - "asked" # simple past tense

q_yell:
 - "(had yelled)" # preterite past tense
 - "((am|be|was|were) yellin('|g))" # be V+ing
 - "yell" # Non-3sing present, habitual
 - "yells" # 3sing present
 - "yellin('|g)" # V+ing
 - "yelled" # simple past tense

q_repeat:
 - "(had repeated)" # preterite past tense
 - "((am|be|was|were)repeatin('|g))" # be V+ing
 - "repeat" # Non-3sing present, habitual
 - "repeats" # 3sing present
 - "repeatin('|g)" # V+ing
 - "repeated" # simple past tense

copula: # forms of copula for combination with 'all' or 'like'
 - "(had been)" # preterite past tense
 - "((am|be|was|were) bein('|g))" # be V+ing
 - "be" # unmarked
 - "been" # present perfect, remote time
 - "bein('|g)" # V+ing
 - "is" # 3sing present
 - "was" # past
 - "were" # plural past

contracted_copula: # contracted forms of copula
 - "I'm"
 - "we're"
 - "he's"
 - "she's"

pron: # bare q_all/q_like must be preceded by pronouns
 - "I" # 1P-sing
 - "we" #1P-PL
 - "she" #3sing
 - "he" #3sing
 - "they" #3PL

intj:
 - ah
 - ay
 - eh
 - ha
 - hey
 - hm
 - huh
 - man
 - mm
 - oh
 - uh
 - um
 - yo
 - wow