q_say:
  - "say"
  - "says"
  - "saying"
  - "said"

q_go:
  - "go"
  - "goes"
  - "went"

q_tell: # must be followed by an object
 - "tell"
 - "tells"
 - "telling"
 - "told"

copula: # forms of copula for combination with 'all' or 'like'
 - "be"
 - "is"
 - "I'm"
 - "'s"
 - "was"
 - "were"

pron: # bare q_all/q_like must be preceded by pronouns
 - "I"
 - "I'm'a"
 - "you"
 - "we"
 - "us"
 - "she"
 - "her"
 - "he"
 - "him"
 - "they"
 - "them"
 - "'em"

intj:
 - ah
 - ay
 - eh
 - ha
 - hey
 - hm
 - huh
 - man
 - mm
 - oh
 - uh
 - um
 - yo
 - wow